# Generated by Django 5.1.4 on 2024-12-28 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_Kr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
