# Generated by Django 5.1.4 on 2024-12-30 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_Kr', '0002_aboutus_is_visible'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('sort', 'name')},
        ),
    ]
